### ISSUE TITLE
Add Tower sensor code

### ISSUE THREAD

**Issue by Spenceroni-Pepperoni** [Robotiators-888/2022Season#25]
Depending on what's decided create code for a banner sensor and or color sensor to stop the tower for when we are about to shoot

**Comment by KevinH45** [comment]
Update: We're using banner sensor.

**Comment by KevinH45** [comment]
@Spenceroni-Pepperoni @liam-a-wms 

https://github.com/Robotiators-888/2022Season/blob/63b7852e800545e819314a906dc4e29de95e0f6a/src/main/java/frc/robot/commands/OrganizeIndexCMD.java#L28-L36

https://github.com/Robotiators-888/2022Season/blob/63b7852e800545e819314a906dc4e29de95e0f6a/src/main/java/frc/robot/commands/teleopIndex.java#L29-L37

These two execute functions should make the index stop when a certain condition is fulfilled, otherwise, keep doing what it's supposed to do. It uses the isFinished() function which returns the isDone value (init value is false). Taking into account that the calling method is button.whileHeld(). Will this work?

**Comment by KevinH45** [comment]
done

**Comment by KevinH45** [comment]
Not done... need to finish organization and discuss possible states of balls.

**Comment by KevinH45** [comment]
Done and merged with main
